language: java
jdk: openjdk11

before_script:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) download

before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean verify -Pintegration-tests
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r target/site/jacoco/jacoco*.xml

after_success:
  - bash <(curl -L https://coverage.codacy.com/get.sh)