language: java
jdk: openjdk11

branches:
  only:
    - master

before_script:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) download

before_install:
  - chmod +x mvnw

install: skip
script:
  - ./mvnw clean verify -Pintegration-tests

after_success:
  - bash <(curl -L https://coverage.codacy.com/get.sh)