version: "3"
services:
  spring-boot-docker:
    image: gfabbi/spring-boot-docker:latest
    ports:
      - "8080:8080"
    env_file:
      - "env/deployment.env"
    healthcheck:
      test: [ "CMD-SHELL", "curl -v --silent http://localhost:8080/actuator/health 2>&1 | grep UP" ]
      interval: 1m
      timeout: 10s
      retries: 3